[theme]
base = "light"
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
runOnSave = false
allowRunOnSave = false
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
toolbarMode = "auto"
showErrorDetails = true